project:
  type: website

website:
  title: "Mini-Project"
  navbar:
    left:
      - href: index.qmd
        text: Flight Story
      - href: about.qmd
        text: Author

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



